mkdir .\obj
mkdir .\obj\custconn
mkdir .\lib

cd .\metrotrk

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\cc_ddh.c -o ..\obj\custconn\cc_ddh.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\cc_gdev.c -o ..\obj\custconn\cc_gdev.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\CircleBuffer.c -o ..\obj\custconn\CircleBuffer.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\dispatch.c -o ..\obj\dispatch.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\dolphin_trk.c -o ..\obj\dolphin_trk.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\dolphin_trk_glue.c -o ..\obj\dolphin_trk_glue.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\flush_cache.c -o ..\obj\flush_cache.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\main_TRK.c -o ..\obj\main_TRK.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\mainloop.c -o ..\obj\mainloop.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\mem_TRK.c -o ..\obj\mem_TRK.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\mpc_7xx_603e.c -o ..\obj\mpc_7xx_603e.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\msg.c -o ..\obj\msg.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\msgbuf.c -o ..\obj\msgbuf.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\msghndlr.c -o ..\obj\msghndlr.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\mslsupp.c -o ..\obj\mslsupp.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\MWCriticalSection_gc.cpp -o ..\obj\custconn\MWCriticalSection_gc.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\MWEvent_gc.c -o ..\obj\custconn\MWEvent_gc.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\MWMutex_gc.c -o ..\obj\custconn\MWMutex_gc.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\custconn\MWTrace.c -o ..\obj\custconn\MWTrace.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\notify.c -o ..\obj\notify.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\nubevent.c -o ..\obj\nubevent.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\nubinit.c -o ..\obj\nubinit.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\serpoll.c -o ..\obj\serpoll.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\string_TRK.c -o ..\obj\string_TRK.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\support.c -o ..\obj\support.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\targcont.c -o ..\obj\targcont.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\target_options.c -o ..\obj\target_options.o

..\bin\mwcceppc.exe -w most -O4,p -func_align 4 -fp hard -Cpp_exceptions off -RTTI off -enum int -use_lmw_stmw on -nodefaults -proc gekko -str reuse,pool -pool off -lang=c -char signed -inline auto,smart,bottomup -gccext on -flag no-cats -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -define PROCESSOR_7455_EXTENSION=1 -define SUPPRESS_WELCOME_MESSAGE=1 -define DEBUG_MSGCMD=0 -define MW_LITTLE_ENDIAN=0 -define MW_BIG_ENDIAN=1 -define MW_HOST_ENDIAN=MW_BIG_ENDIAN -c .\targimpl.c -o ..\obj\targimpl.o

..\bin\mwasmeppc.exe -nodefaults -proc gekko -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -c .\__exception.s -o ..\obj\__exception.o

..\bin\mwasmeppc.exe -nodefaults -proc gekko -gccinc -ir ..\include -define __PPC_DCACHE__=1 -define __PPC_ICACHE__=1 -define __PPC_TGPR__=1 -c .\targsupp.s -o ..\obj\targsupp.o

..\bin\mwldeppc.exe -nodefaults -proc gekko -library -abi eabi -o ..\lib\TRK_Hollywood_Revolution.a ..\obj\__exception.o ..\obj\targsupp.o ..\obj\custconn\cc_ddh.o ..\obj\custconn\cc_gdev.o ..\obj\custconn\MWEvent_gc.o ..\obj\custconn\MWMutex_gc.o ..\obj\custconn\MWTrace.o ..\obj\custconn\MWCriticalSection_gc.o ..\obj\custconn\CircleBuffer.o ..\obj\flush_cache.o ..\obj\main_TRK.o ..\obj\mainloop.o ..\obj\mem_TRK.o ..\obj\dispatch.o ..\obj\dolphin_trk.o ..\obj\dolphin_trk_glue.o ..\obj\notify.o ..\obj\nubevent.o ..\obj\nubinit.o ..\obj\serpoll.o ..\obj\string_TRK.o ..\obj\support.o ..\obj\targcont.o ..\obj\mpc_7xx_603e.o ..\obj\msg.o ..\obj\msgbuf.o ..\obj\msghndlr.o ..\obj\mslsupp.o ..\obj\targimpl.o ..\obj\target_options.o

cd ..